// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrEOoJKsgp6eQS_ck3Jou5Rorj1TskVB4',
    appId: '1:583482364138:web:3d7fbd2a78359d77828793',
    messagingSenderId: '583482364138',
    projectId: 'salesbet-7deb2',
    authDomain: 'salesbet-7deb2.firebaseapp.com',
    storageBucket: 'salesbet-7deb2.firebasestorage.app',
    measurementId: 'G-V4MZ33W9D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjXc-SYBa0RMzVbnQ4lNtoGLY7T3fbdN4',
    appId: '1:583482364138:android:fba58bb6de10f445828793',
    messagingSenderId: '583482364138',
    projectId: 'salesbet-7deb2',
    storageBucket: 'salesbet-7deb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUXVqtgh0amsXOX_FCK5uhtN40TPVt4LU',
    appId: '1:583482364138:ios:20a294e33bce6027828793',
    messagingSenderId: '583482364138',
    projectId: 'salesbet-7deb2',
    storageBucket: 'salesbet-7deb2.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUXVqtgh0amsXOX_FCK5uhtN40TPVt4LU',
    appId: '1:583482364138:ios:20a294e33bce6027828793',
    messagingSenderId: '583482364138',
    projectId: 'salesbet-7deb2',
    storageBucket: 'salesbet-7deb2.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrEOoJKsgp6eQS_ck3Jou5Rorj1TskVB4',
    appId: '1:583482364138:web:5d79a66bed012b53828793',
    messagingSenderId: '583482364138',
    projectId: 'salesbet-7deb2',
    authDomain: 'salesbet-7deb2.firebaseapp.com',
    storageBucket: 'salesbet-7deb2.firebasestorage.app',
    measurementId: 'G-CHPCLBXBFT',
  );
}
